### ISSUE TITLE
Not compatible shader files with BetterHUD plugin

### ISSUE THREAD

**Issue by PSYCHEER** [JNNGL/VanillaMinimaps#15]
As soon as I installed my HUD from BetterHud was disabled(invisible) bcz plugin uses some shaders which make this HUD invisible. Not usable for me.. I need HUD with minimap.

**Comment by JNNGL** [comment]
You have to merge the shaders.

**Comment by KamikotoTkach** [comment]
> You have to merge the shaders.

Это какая-то фича BetterHud или имеется в виду вручную мержить?
