### ISSUE TITLE
Map displayed above and below character's head.

### ISSUE THREAD

**Issue by byteveil** [JNNGL/VanillaMinimaps#3]
![image](https://github.com/JNNGL/VanillaMinimaps/assets/152559788/6ea6130d-c745-40c5-8e93-175b855fd622)
![image](https://github.com/JNNGL/VanillaMinimaps/assets/152559788/eefc5a1b-f888-4090-888a-d8e2db9a1f3d)

**Comment by byteveil** [comment]
I might be a fool because I did not see the resource pack. Let me check if that's why.

**Comment by byteveil** [comment]
Same thing happens with the resource pack:

![image](https://github.com/JNNGL/VanillaMinimaps/assets/152559788/cf2bcace-7003-4330-8d14-a6440ef4f77a)

**Comment by JNNGL** [comment]
Any mods installed?

**Comment by byteveil** [comment]
No.--Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 1/31/24, 9:42 AM JNNGL ***@***.***> wrote:

   
  Any mods installed?

**Comment by byteveil** [comment]
> Any mods installed?

No. Tested with and without Sodium.

**Comment by ventusjs** [comment]
Hi, i have the same problem with the plugin, and its installed with the reource pack, but in game looks like the picture on top, can you help us please?

**Comment by shawnjb** [comment]
Okay, so even though I don't have any mods installed, I notice that the README states 1.20.4 as the required server version, and mine is running on that version, but it's with Paper. Are there any potential conflicts between Vanilla Minimaps and Paper's server?

**Comment by daretmavi** [comment]
Same issue wit paper-1.20.4-422

Other plugins are installed:
UserLogin
FastLogin
ProtocolLib
LuckPerms
GriefPrevention
SkinsRestorer
BurgerHud
Graves
Dynmap
Fast Chunk Pregenerator
View Distance Tweaks
Bookshelf
Books without Borders Updated
Custom Compass
Little Composter
NotTooExpensive
Thizzy'z Tree Feller
Invisible Item Frames
Wandering Trades
Ez Chest Shop
Vault
BetterEconomy
InteractionVisualizer

**Comment by Algiuxs** [comment]
same here with papermc on rpi5

**Comment by AlexanderwithaA** [comment]
well, here I am, same issue

**Comment by grat2** [comment]
Also here with the same issue on paper 1.20.4-496
