### ISSUE TITLE
Possible to merge shaders core?

### ISSUE THREAD

**Issue by Sodies** [JNNGL/VanillaMinimaps#4]
I happy happyhud installed. And your minimap shader collide with happyhud shaders. Please help to make it compatible

**Comment by vadim-soude** [comment]
It's not as easy as that, the shader Jnngl made uses common files used by many vanilla shaders. 

If you are wiling to invest the time you could check each file and see if you can make it work but asking Jnngl to make it compatible with every shader you could throw at it ins't feasible.
